services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: payment-redis
    ports:
      - "6379:6379"

  payment-platform-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-platform-api
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: payment_user
      DB_PASSWORD: payment_pass
      DB_NAME: payment_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OUTBOX_PUBLISHER_ENABLED: "false"
      PAYMENT_CONSUMER_ENABLED: "false"
    depends_on:
      - postgres
      - redis

  payment-platform-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-platform-worker
    command: ["node", "dist/worker.js"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: payment_user
      DB_PASSWORD: payment_pass
      DB_NAME: payment_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OUTBOX_PUBLISHER_ENABLED: "true"
      PAYMENT_CONSUMER_ENABLED: "true"
      QUEUE_PROVIDER: sqs
      AWS_REGION: us-east-1
      SQS_ENDPOINT: http://localstack:4566
      SQS_QUEUE_NAME: payment-events
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      localstack:
        condition: service_healthy
  localstack:
    image: localstack/localstack:3.8.1
    container_name: payment-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  payment_postgres_data: