### Crear pago
POST http://localhost:3000/payments
Content-Type: application/json

{
  "idempotencyKey": "idem-026",
  "customerId": "customer-123",
  "merchantId": "merchant-456",
  "qrData": "000201",
  "amountInCents": 150050,
  "currency": "ARS"
}

### Obtener un pago por ID
GET http://localhost:3000/payments/a739beea-3f6d-4d65-ae27-3e5393e37d58
Accept: application/json
