### Crear pago
POST http://localhost:3000/payments
Content-Type: application/json

{
  "idempotencyKey": "idem-correlation-004",
  "correlationId": "corr-002",
  "customerId": "customer-123",
  "merchantId": "merchant-456",
  "qrData": "000201010212...",
  "amountInCents": 150050,
  "currency": "ARS"
}

### Obtener un pago por ID
GET http://localhost:3000/payments/4830b932-4933-4404-90d6-89165edc9d69
Accept: application/json

### Health
# curl http://localhost:3000/health
GET http://localhost:3000/health

### READY ?


# curl http://localhost:3000/health/ready
GET http://localhost:3000/health/ready

### REDIS ok ?

# curl http://localhost:3000/health/ready
GET http://localhost:3000/health/ready

