### Crear pago
POST http://localhost:3000/payments
Content-Type: application/json

{
  "idempotencyKey": "idem-correlation-001",
  "correlationId": "corr-001",
  "customerId": "customer-123",
  "merchantId": "merchant-456",
  "qrData": "000201010212...",
  "amountInCents": 150050,
  "currency": "ARS"
}

### Obtener un pago por ID
GET http://localhost:3000/payments/409bbd70-5574-4040-a9d3-a03308984030
Accept: application/json

### Health
# curl http://localhost:3000/health
GET http://localhost:3000/health

### READY ?


# curl http://localhost:3000/health/ready
GET http://localhost:3000/health/ready

### REDIS ok ?

# curl http://localhost:3000/health/ready
GET http://localhost:3000/health/ready

